# Generated by Django 3.0.7 on 2020-06-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='fuel_tank',
            new_name='passenger',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='consumption_per_minute',
        ),
    ]
